### ISSUE TITLE
Wrong Icon?

### ISSUE THREAD

**Issue by ProgressX** [fatfingers23/RuneliteOfflineChatIcon#1]
I think my icon is no longer the red arrow, but is appearing as Graardor? Lol. Asked the person if it could be something else like leagues/being on a specialty world symbol but they couldn't see it and thought I was crazy.

Assuming they hopped worlds, it appeared, then chatted when they settled in a world. Has been happening most of the day and when I notice it the people are usually logged out.

![image](https://github.com/fatfingers23/RuneliteOfflineChatIcon/assets/75743643/ec7ec81e-3623-4a30-ae09-80fb99f09b6b)

**Comment by fatfingers23** [comment]
Haha, yeah, it is a bit of an odd bug, and I'm not sure how to fix it; a few other plugins do it, too, sometimes with icons.

In the code, when you pick an icon, as far as I know, there is no way to get it by name, so you can't go like load `offline_icon_.png`; you have to do `Load icon number 50 of 100 icons`. Sometimes, a plugin's count of which number their icon is gets off and loads a different one. Always a bit funny when it comes up.

**Comment by ProgressX** [comment]
> Haha, yeah, it is a bit of an odd bug, and I'm not sure how to fix it; a few other plugins do it, too, sometimes with icons.
> 
> In the code, when you pick an icon, as far as I know, there is no way to get it by name, so you can't go like load `offline_icon_.png`; you have to do `Load icon number 50 of 100 icons`. Sometimes, a plugin's count of which number their icon is gets off and loads a different one. Always a bit funny when it comes up.

Haha gotcha. Was a fun surprise for sure, but back to normal now. Thanks for checking in.
